"use client";

import { useEffect, useState } from "react";
import { useReadContract, useAccount } from "wagmi";
import { formatEther, formatUnits, isAddress, type Address } from "viem";
import { useBurn } from "@/hooks/useBurn";
import { ERC20_ABI } from "@/lib/abis/erc20";
import { BurnForm } from "./BurnForm";
import { Stepper } from "./Stepper";
import { TokenSelector } from "./TokenSelector";

type Step = "idle" | "approving" | "burning" | "done";

export function IncineratorModule() {
  const { address, isConnected } = useAccount();
  const [token, setToken] = useState("");
  const [amount, setAmount] = useState("");
  const [step, setStep] = useState<Step>("idle");
  const [error, setError] = useState<string | null>(null);

  const validToken = isAddress(token) ? (token as Address) : undefined;

  const { burn, executeBurn, approveConfirmed, flatFee, isPending, isSuccess, txHash } =
    useBurn(validToken);

  const { data: tokenSymbol } = useReadContract({
    address: validToken,
    abi: ERC20_ABI,
    functionName: "symbol",
    query: { enabled: Boolean(validToken) },
  });
  const { data: tokenDecimals } = useReadContract({
    address: validToken,
    abi: ERC20_ABI,
    functionName: "decimals",
    query: { enabled: Boolean(validToken) },
  });
  const { data: tokenBalance } = useReadContract({
    address: validToken,
    abi: ERC20_ABI,
    functionName: "balanceOf",
    args: address ? [address] : undefined,
    query: { enabled: Boolean(validToken && address) },
  });

  // Drive the step state machine off the wagmi hooks rather than during render.
  useEffect(() => {
    if (approveConfirmed && step === "approving") setStep("burning");
  }, [approveConfirmed, step]);

  useEffect(() => {
    if (isSuccess && step === "burning") setStep("done");
  }, [isSuccess, step]);

  const handleApprove = () => {
    if (!validToken) return;
    setError(null);
    setStep("approving");
    try {
      burn(validToken, amount);
    } catch (e) {
      setError(formatErr(e));
      setStep("idle");
    }
  };

  const handleBurn = () => {
    if (!validToken) return;
    setError(null);
    setStep("burning");
    try {
      executeBurn(validToken, amount);
    } catch (e) {
      setError(formatErr(e));
      setStep("approving");
    }
  };

  const reset = () => {
    setStep("idle");
    setAmount("");
    setError(null);
  };

  const apiUrl = process.env.NEXT_PUBLIC_API_URL;

  return (
    <div className="max-w-2xl mx-auto px-2 animate-fade-in">
      <header className="text-center mt-6 mb-8">
        <div className="text-5xl mb-3">🔥</div>
        <h1 className="text-3xl font-bold tracking-tight mb-2">Incinerator</h1>
        <p className="text-slate-400 max-w-md mx-auto">
          Burn worthless ERC-20 tokens for $RCY rewards and a Loss Certificate NFT.
        </p>
        {flatFee != null && (
          <div className="mt-4 inline-flex items-center gap-2">
            <span className="pill-yellow">
              Fee: {formatEther(flatFee as bigint)} BNB
            </span>
          </div>
        )}
      </header>

      <Stepper current={step} />

      {!isConnected ? (
        <div className="card p-10 text-center">
          <div className="text-4xl mb-3">👛</div>
          <h2 className="text-lg font-semibold mb-1">Connect your wallet</h2>
          <p className="text-slate-400 text-sm">
            Use the button in the top-right to connect.
          </p>
        </div>
      ) : step === "done" ? (
        <div className="card p-8 text-center animate-slide-up">
          <div className="text-5xl mb-3">✅</div>
          <h2 className="text-xl font-semibold mb-1">Tokens incinerated</h2>
          <p className="text-slate-400 text-sm mb-6">
            Your Loss Certificate has been minted on-chain.
          </p>

          <div className="bg-slate-900/60 border border-slate-800 rounded-xl p-4 mb-6 text-left text-xs font-mono break-all">
            <div className="text-slate-500 uppercase tracking-wider text-[10px] mb-1">
              Transaction
            </div>
            {txHash}
          </div>

          <div className="flex flex-col sm:flex-row gap-3 justify-center">
            <a
              href={`${apiUrl}/certificates/${txHash}`}
              target="_blank"
              rel="noreferrer"
              className="btn-primary"
            >
              ⬇ Download certificate (PDF)
            </a>
            <button onClick={reset} className="btn-ghost">
              Burn more
            </button>
          </div>

          <p className="text-xs text-slate-600 mt-4">
            The certificate is generated by the indexer. May take a few seconds to be ready.
          </p>
        </div>
      ) : (
        <div className="space-y-4 animate-slide-up">
          <div className="card p-6 space-y-5">
            <TokenSelector
              owner={address}
              selected={token}
              onSelect={(addr) => { setToken(addr); setAmount(""); }}
            />

            <BurnForm
              amount={amount}
              step={step}
              isPending={isPending}
              symbol={tokenSymbol as string | undefined}
              decimals={tokenDecimals as number | undefined}
              balance={tokenBalance as bigint | undefined}
              tokenIsValid={Boolean(validToken)}
              onAmountChange={setAmount}
              onApprove={handleApprove}
              onBurn={handleBurn}
            />
          </div>

          {error && (
            <div className="card p-4 border-red-500/40 bg-red-500/5 text-sm text-red-200">
              <strong className="text-red-300">Error:</strong> {error}
            </div>
          )}

          {tokenDecimals != null && tokenBalance != null && (
            <div className="text-xs text-slate-500 text-center">
              Detected {String(tokenSymbol ?? "TOKEN")} with {String(tokenDecimals)} decimals ·{" "}
              balance {formatUnits(tokenBalance as bigint, Number(tokenDecimals))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

function formatErr(e: unknown): string {
  if (e instanceof Error) return e.message.split("\n")[0];
  return String(e);
}
